name: Lighthouse CI
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Chrome Headless
        run: |
          google-chrome-stable --headless --no-sandbox --remote-debugging-port=9222 &

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            https://uk.kineticasports.com/
            https://uk.kineticasports.com/blogs/news/when-should-you-take-creatine
            https://uk.kineticasports.com/products/creatine
            https://uk.kineticasports.com/collections/whey-protein-powder
          configPath: "./lighthouse/lighthouserc.json"
          uploadArtifacts: true
          chromeFlags: '--no-sandbox --headless --disable-gpu'
        env:
          DEBUG: "true"
