name: Lighthouse CI
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        google-chrome --version

    - name: Run Lighthouse
      uses: treosh/lighthouse-ci-action@v3
      with:
        urls: |
              https://uk.kineticasports.com/
              https://uk.kineticasports.com/blogs/news/when-should-you-take-creatine
              https://uk.kineticasports.com/products/creatine
              https://uk.kineticasports.com/collections/whey-protein-powder
        configPath: './lighthouse/lighthouserc.json'
        uploadArtifacts: true
      env:
        DEBUG: "true"

